# Generated by Django 4.2.27 on 2026-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1234567890, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
