# Generated by Django 4.2.27 on 2026-02-05 10:36

from django.db import migrations, models
import internships.models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipregistration',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='resume',
            field=models.FileField(default='timezone.now', help_text='Upload your resume (PDF, DOC, DOCX)', upload_to=internships.models.resume_upload_path),
            preserve_default=False,
        ),
    ]
