# Generated by Django 4.2.27 on 2026-02-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_feedbac_e1d362_idx',
            old_name='feedback_fe_feedb_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_user_id_22e651_idx',
            old_name='feedback_fe_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='feedback_fe_rating_c20163_idx',
            old_name='feedback_fe_rating_idx',
        ),
    ]
