# Generated by Django 4.2.27 on 2026-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_feedback_fe_feedb_idx_feedback_fe_feedbac_e1d362_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
