# Generated by Django 4.2.27 on 2026-02-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_rating_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='feedback_fe_rating_c20163_idx',
        ),
    ]
