# Generated by Django 4.2.27 on 2026-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membershiptier_membershipregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipregistration',
            name='notes',
        ),
        migrations.AddField(
            model_name='membershipregistration',
            name='reason',
            field=models.TextField(blank=True, help_text="User's reason for joining/interest in membership", null=True),
        ),
    ]
