# Generated by Django 4.2.27 on 2026-02-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_membershipregistration_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
