# Generated by Django 4.2.27 on 2026-02-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membershipregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipregistration',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='membershipregistration',
            name='renewal_count',
        ),
    ]
