# Generated by Django 4.2.27 on 2026-02-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_remove_membershipregistration_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
    ]
