# Generated by Django 4.2.27 on 2026-02-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshihips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='status',
            new_name='is_active',
        ),
    ]
