# Generated by Django 4.2.27 on 2026-02-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshihips', '0003_internshipregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='internshipregistration',
            new_name='internshihi_status_36c109_idx',
            old_name='internshihi_status_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='internshipregistration',
            new_name='internshihi_user_id_d50da5_idx',
            old_name='internshihi_user_id_d4e5f6_idx',
        ),
    ]
