# Generated by Django 4.2.27 on 2026-02-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshihips', '0004_rename_internshihi_status_a1b2c3_idx_internshihi_status_36c109_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipregistration',
            name='available_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='current_institution',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='expected_start_date',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='interviewer_notes',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='major_or_field',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='internshipregistration',
            name='skill_tags',
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
