# Generated by Django 4.2.27 on 2026-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshihips', '0005_remove_internshipregistration_available_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipregistration',
            name='reason',
            field=models.TextField(blank=True, help_text="User's reason for applying/interest in internship", null=True),
        ),
    ]
