# Generated by Django 4.2.27 on 2026-02-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshihips', '0006_internshipregistration_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='event_date',
            field=models.DateField(),
        ),
    ]
