# Generated by Django 4.2.27 on 2026-02-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_webinarregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarregistration',
            name='notes',
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='reason',
            field=models.TextField(blank=True, help_text="User's reason for registering/interest in webinar", null=True),
        ),
    ]
