# Generated by Django 4.2.27 on 2026-02-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_remove_webinarregistration_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='event_date',
            field=models.DateField(),
        ),
    ]
