# Generated by Django 4.2.27 on 2026-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_alter_webinar_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarregistration',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='feedback_given_at',
        ),
        migrations.RemoveField(
            model_name='webinarregistration',
            name='rating',
        ),
    ]
